build-umd:
	rollup ../src/index.js --file build/poker-hand.js --format umd --name "PokerHand"

build-iife:
	rollup ../src/index.js --file build/poker-hand.mjs --format umd --name "iife"

build-cjs:
	rollup ../src/index.js --file build/poker-hand.mjs --format cjs


